import {
  DashboardOutlined,
  ProfileOutlined,
  SettingOutlined,
  PieChartOutlined,
  TeamOutlined,
  FundViewOutlined,
  SearchOutlined,
  UserOutlined,
  UserAddOutlined,
  ThunderboltOutlined,
  ShopOutlined,
  SolutionOutlined,
  StarOutlined,
  GiftOutlined,
  RobotOutlined,
  FieldTimeOutlined,
  CommentOutlined,
} from '@ant-design/icons';

export const router: MenuListType[] = [
  {
    type: 'group',
    label: '대시보드',
  },
  {
    path: '/',
    label: '실시간',
    page: '대시보드 - 실시간',
    icon: DashboardOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/',
    label: '대시보드',
    page: '대시보드',
    icon: DashboardOutlined,
    haveAuthority: ['agent'],
  },
  {
    path: '/monitor',
    label: '모니터링',
    page: '모니터링',
    icon: FundViewOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/report',
    label: '리포트',
    page: '리포트',
    icon: PieChartOutlined,
    haveAuthority: ['super', 'admin'],
  },
  { type: 'divider' },
  {
    type: 'group',
    label: '티켓',
  },
  {
    path: '/ticket',
    label: '티켓 조회',
    page: '티켓 조회',
    icon: SearchOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/ticket',
    label: '나의 티켓',
    page: '나의 티켓',
    icon: ProfileOutlined,
    haveAuthority: ['agent'],
  },
  {
    path: '/ticket/setting',
    label: '티켓 설정',
    page: '티켓 설정',
    icon: ProfileOutlined,
    haveAuthority: ['super', 'admin'],
  },
  { type: 'divider' },
  {
    type: 'group',
    label: '관리',
  },
  {
    path: '/team',
    label: '팀',
    page: '팀',
    icon: TeamOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/member',
    label: '팀원 관리',
    page: '팀원 관리',
    icon: UserAddOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/manager',
    label: '관리자',
    page: '관리자',
    icon: SolutionOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/counselor',
    label: '상담사',
    page: '상담사',
    icon: UserOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/message',
    label: '챗봇 메세지',
    page: '챗봇 메세지',
    icon: CommentOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/answer',
    label: '빠른답변',
    page: '빠른답변',
    icon: ThunderboltOutlined,
    haveAuthority: ['super', 'admin', 'agent'],
  },
  {
    path: '/branch',
    label: '점포공감',
    page: '점포공감',
    icon: ShopOutlined,
    haveAuthority: ['super', 'admin', 'agent'],
  },
  {
    path: '/roadshow',
    label: '로드쇼',
    page: '로드쇼',
    icon: StarOutlined,
    haveAuthority: ['super', 'admin', 'agent'],
  },
  { type: 'divider', haveAuthority: ['super', 'admin'] },
  {
    type: 'group',
    label: '설정',
    haveAuthority: ['super', 'admin'],
  },
  {
    path: 'general',
    label: '일반 설정',
    icon: SettingOutlined,
    haveAuthority: ['super', 'admin'],
    children: [
      {
        path: '/general',
        label: '일반',
        page: '일반',
      },
      {
        path: '/general/auto',
        label: '자동화',
        page: '자동화',
      },
      {
        path: '/general/rank',
        label: '직급',
        page: '직급',
      },
      {
        path: '/general/abusive',
        label: '욕설필터',
        page: '욕설필터',
      },
    ],
  },
  {
    path: '/operation',
    label: '운영 시간 설정',
    page: '운영 시간 설정',
    icon: FieldTimeOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: '/chatbot',
    label: '챗봇 설정',
    page: '챗봇 설정',
    icon: RobotOutlined,
    haveAuthority: ['super', 'admin'],
  },
  {
    path: 'event',
    label: '타임 이벤트',
    page: '타임 이벤트',
    icon: GiftOutlined,
    haveAuthority: ['super', 'admin'],
    children: [
      {
        path: '/event/time',
        label: '타임 이벤트',
        page: '타임 이벤트',
      },
      {
        path: '/event/instantly',
        label: '즉시 이벤트',
        page: '즉시 이벤트',
      },
    ],
  },
];
