'use client';

import React, { ReactNode, useEffect, useRef, useState } from 'react';
import {
  legacyLogicalPropertiesTransformer,
  px2remTransformer,
  createCache,
  extractStyle,
  StyleProvider,
} from '@ant-design/cssinjs';
import { useServerInsertedHTML } from 'next/navigation';
import { ConfigProvider } from 'antd';
import { themeAntModes, themeConfig } from '@/theme/config';
import ko from 'antd/locale/ko_KR';
import '@/styles/index.scss';

const Registry = ({
  children,
  themeMode,
}: {
  children: ReactNode;
  themeMode: any;
}) => {
  const prefix: string = 'qt';
  const cache = createCache();
  const inserted = useRef(false);
  const px2rem = px2remTransformer({
    rootValue: 10, // 10px = 1rem;
  });

  useServerInsertedHTML(() => {
    const styleText = extractStyle(cache, { plain: true });

    if (inserted.current) {
      return null;
    }
    inserted.current = true;

    return (
      <style
        id={`${prefix}-cssinjs`}
        // to make sure this style is inserted before Ant Design's style generated by client
        data-rc-order="prepend"
        data-rc-priority="-1000"
        dangerouslySetInnerHTML={{ __html: styleText }}
      />
    );
  });

  return (
    <StyleProvider
      transformers={[legacyLogicalPropertiesTransformer, px2rem]}
      hashPriority="high"
      cache={cache}
      autoClear
    >
      <ConfigProvider
        theme={{ algorithm: themeAntModes[themeMode], ...themeConfig }}
        prefixCls={prefix}
        iconPrefixCls={prefix}
        locale={ko}
      >
        {children}
      </ConfigProvider>
    </StyleProvider>
  );
};

export default Registry;
