import clsx from 'clsx';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import Registry from '@/theme/registry';

const noto = Noto_Sans_KR({ weight: ['400', '700'], subsets: ['latin'] });
// const colorMode = 'light';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          noto.className,
          'antialiased',
          'quantum',
          // `qt-${colorMode}`,
        )}
      >
        <Registry>{children}</Registry>
      </body>
    </html>
  );
}
